# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Главная
    url: /#top
    weight: 10
  - name: О проекте
    url: /#features
    weight: 20
  - name: Информация
    weight: 40
    url: blog/
