main:
  - name: Главная
    url: /#top
    weight: 10
  - name: О проекте
    url: /#features
    weight: 20
  - name: Информация
    weight: 40
    url: blog/
  - name: Авторизация
    weight: 50
    url: authorization
    id: auth-link
  - name: Выход
    weight: 50 
    url: /logout
    id: logout-link
    params:
      class: hidden